data_source: 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

data: 
  data_source: 'from_ics'
  raw_folder: 'raw_format'
  file: 'redwine.csv'
  split_data: 'pepared'
  train: 'train.csv'
  test: 'test.csv'


model:
  - folder: 'pickle'
    model: 'LRTrained.pkl'